version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/adgile

#permissions:
#  - object: /home/ubuntu/example

hooks:
  # AfterInstall 은 배포를 완료한 후 실행되는 스크립트를 명시하며
  # ApplicationStart 나 ValidateService 등을 대신 쓸 수 있다.
  AfterInstall:
    - location: script/application-start.sh
      timeout: 60
      runas: root